/** This file is automatically generated by webpack plugins, no not edit
 *
 * In ui/ui.ts, import this file
 * import { Imports, RegisterFunction } from "./ui_types";
 */
export * from "../../workspace/ui_exports";
